title:              Radiyah Sabur
email:              rsabur58@gmail.com
description:        "Full-stack software engineer experienced in Ruby, JavaScript, Java and Python based languages with a passion for fashion and travel
____________________________________________________________________


React.js | React-Native | Node.js | Express.js | Rails | TypeScript | HTML/CSS | Git"

author:             Radiyah Sabur
# baseurl:            "https://radiyahsabur.com"
url:                "https://radiyahsabur.com"

# Social Profiles
linkedin_username: radiyahsabur
github_username:    rsabur
instagram_username: radiyahsabur 
twitter_username:   radiyahsabur
# facebook_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
